# Set site parameters
SITE_NAME = 'FurtherPerception'
# Set person parameters
EMAIL_LENGTH_MAXIMUM = 48
NICKNAME_LENGTH_MINIMUM = 3
NICKNAME_LENGTH_MAXIMUM = 32
USERNAME_LENGTH_MINIMUM = 6
USERNAME_LENGTH_MAXIMUM = 32
PASSWORD_LENGTH_MINIMUM = 6
PASSWORD_LENGTH_AVERAGE = 16
TICKET_LENGTH = 32
TICKET_LIFESPAN_IN_DAYS = 1
REJECTION_LIMIT = 3
# Set generic parameters
NAME_LENGTH_MINIMUM = 6
NAME_LENGTH_MAXIMUM = 128
